# Generated by Django 6.0.4 on 2026-04-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['id']},
        ),
    ]
