# Generated by Django 6.0.4 on 2026-04-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='Товар', max_length=200, verbose_name='Название товара'),
        ),
    ]
